language: php
git:
  depth: 2
sudo: false

php:
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest;
  - travis_retry composer dump-autoload

before_script:
  - cp .env.travis .env
  - travis_retry php artisan key:generate
  - travis_retry php artisan optimize

script: vendor/bin/phpunit

branches:
  only:
    - master
