language: php
git:
  depth: 2
sudo: false

php:
  - 7.1

env:
  - DB_CONNECTION=testing
  - DB_CONNECTION=testing_travis

addons:
  postgresql: "9.4"

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest;
  - travis_retry composer dump-autoload

before_script:
  - cp .env.travis .env
  - psql -c 'create database travis_ci_test;' -U postgres
  - travis_retry php artisan key:generate
  - travis_retry php artisan optimize

script: vendor/bin/phpunit

branches:
  only:
    - master
